spring:
  application:
    name: restaurant-management-system
  security:
    user:
      name: admin
      password: 1234

server:
  port: 8181

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info