spring:
  application:
    name: restaurant-management-system
  profiles:
    active: local
  security:
    user:
      name: admin
      password: 1234

server:
  port: 8282

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info