pipeline {

    agent any

    tools {
        maven 'Maven 3.9'
    }

    environment {
        APP_NAME     = "restaurant-management"
        IMAGE_REPO   = "phalraksa/restaurant-management"
        IMAGE_TAG    = "${env.GIT_COMMIT[0..6]}"   // short SHA e.g. a3f91bc
        DOCKER_IMAGE = "${IMAGE_REPO}"
        DOCKER_CREDS = "dockerhub-creds"
    }

    stages {

        stage('Build JAR') {
            steps {
                sh 'chmod +x mvnw'
                sh './mvnw package -B -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_IMAGE ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "$DOCKER_CREDS",
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push $DOCKER_IMAGE"
            }
        }

        stage('Deploy to Docker Compose') {
            steps {
                withCredentials([
                    string(credentialsId: 'postgres-password', variable: 'DB_PASS')
                ]) {
                    sh '''
                        echo "🚀 Deploying with Docker Compose..."

                        # Stop old containers (optional but safer)
                        docker compose down || true

                        # Start new version
                        docker compose up -d
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployed ${IMAGE_TAG} successfully"
        }
        failure {
            echo "❌ Deployment of ${IMAGE_TAG} failed rolled back automatically"
        }
        always {
            sh 'docker logout || true'
            cleanWs()
        }
    }
}

